### PR TITLE
Add net and meter info

### PR DESCRIPTION
**Pull request by APayerl**
Added reference to mälarenergi as a net provider and info regarding one of their meters.

### CODE REVIEW

**Comment by APayerl** [comment]
Could you please check the link from mälarenergi net to the meter I added? I can't seem to be able to verify the link...

**Comment by Krolken** [comment]
Link works. But no picture of the meter.
Is it a Norwegian or Swedish port? I know Kaifa on the west coast is using the norwergian standard.

**Comment by APayerl** [comment]
it's a RJ45 port.

**Comment by Krolken** [comment]
OK. Maybe it would be good to add "Kaifamätaren använder den norska standarden (RJ45) för HAN-port)"

**Comment by APayerl** [comment]
Sure!

**Pull request merged**
